services:
  gateway.api:
    container_name: gateway
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: Gateway/Gateway.Api/Dockerfile
  postgres:
    image: postgres
    container_name: postgresDB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  postgres-vol: